spring:
  security:
    user:
      name: user
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    include: mysql

logging:
  level:
    org.springframework.security: DEBUG
